name: flutter_controle_abastecimento
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  rxdart: ^0.28.0
  firebase_core: ^3.8.0
  firebase_data_connect: ^0.1.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
