// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc2ixEbUOYtNK7pRekJzGIM3qVTw9BXgU',
    appId: '1:807751903956:web:1c2a39a2840930ff2d6941',
    messagingSenderId: '807751903956',
    projectId: 'flutter-controle-abastecimento',
    authDomain: 'flutter-controle-abastecimento.firebaseapp.com',
    storageBucket: 'flutter-controle-abastecimento.firebasestorage.app',
    measurementId: 'G-Z6ZE9SG23T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkFHi4GmHWxS7Q9bkMke7BxT4NSPo0XUs',
    appId: '1:807751903956:android:dbf710b26e595f692d6941',
    messagingSenderId: '807751903956',
    projectId: 'flutter-controle-abastecimento',
    storageBucket: 'flutter-controle-abastecimento.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcWXSEna-LTYjbH3Ni1N70G7LjDSK28Nk',
    appId: '1:807751903956:ios:d2cdb6eb4ee524272d6941',
    messagingSenderId: '807751903956',
    projectId: 'flutter-controle-abastecimento',
    storageBucket: 'flutter-controle-abastecimento.firebasestorage.app',
    iosBundleId: 'com.example.flutterControleAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcWXSEna-LTYjbH3Ni1N70G7LjDSK28Nk',
    appId: '1:807751903956:ios:d2cdb6eb4ee524272d6941',
    messagingSenderId: '807751903956',
    projectId: 'flutter-controle-abastecimento',
    storageBucket: 'flutter-controle-abastecimento.firebasestorage.app',
    iosBundleId: 'com.example.flutterControleAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc2ixEbUOYtNK7pRekJzGIM3qVTw9BXgU',
    appId: '1:807751903956:web:830040ce0ff6c3f72d6941',
    messagingSenderId: '807751903956',
    projectId: 'flutter-controle-abastecimento',
    authDomain: 'flutter-controle-abastecimento.firebaseapp.com',
    storageBucket: 'flutter-controle-abastecimento.firebasestorage.app',
    measurementId: 'G-8ZCXHPHVVT',
  );
}
